In [4]:
import numpy as np

# 1-Dimensional

In [6]:
# 1-dimensional array
a=np.array([1,2,3,4])
print(a)
print(a.ndim)

[1 2 3 4]
1


In [19]:
# create numpy through zeros
z=np.zeros(10)
print(z)

z1=np.zeros(10,dtype=np.int32)
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [20]:
# create numpy through ones
o=np.ones(10)
print(o)

o1=np.ones(10,dtype=np.int32)
print(o1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [14]:
# create numpy through empty
em=np.empty(10)
em

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# create numpy through arrange
ar=np.arange(10)                                     #range(by default start from 0)
print(ar)

ar1=np.arange(1,20)                                   # start from 1 and end with 20 but n-1
print(ar1)

ar2=np.arange(1,20,3)                                    #start from 1, end point is 20 and gap is 3
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  4  7 10 13 16 19]


In [18]:
# create numpy with linespace(linearly space array)
l=np.linspace(1,20,num=5)
l

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

# 2-Dimensional

In [7]:
# 2-dimensional array
b=np.array([[2,4,5,6],[3,1,0,8]])
print(b)
print(b.ndim)

[[2 4 5 6]
 [3 1 0 8]]
2


In [23]:
ze=np.zeros((2,4))
print(ze)

ze1=np.zeros((3,5),dtype=np.int32)
print(ze1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [24]:
on=np.ones((4,5))
print(on)

on=np.ones((4,5),dtype=np.int32)
print(on)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
e=np.empty((3,5),dtype=np.int32)
print(e)

[[4128860 6029375 3801155 5570652 6619251]
 [7536754 4718684 6029392 7340097 4456560]
 [7602273 6029409 7274572 6357091 6029420]]


# 3-Dimensional

In [34]:
# 3-dimensional array
c=np.array([[[1,2,4,7],[9,5,4,3],[2,3,5,6],[2,3,5,6]]])
print(c)
print(c.ndim)

[[[1 2 4 7]
  [9 5 4 3]
  [2 3 5 6]
  [2 3 5 6]]]
3


In [36]:
a3=np.arange(24).reshape(2,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Array Methods

In [40]:
# shape
arr=np.array([[2,6,7,8],[4,5,68,9]])
b.shape

(2, 4)

In [44]:
# check indexes     
# arr is 2d array: 0 is for 1st array and 1 is for 2nd array
arr[1,3]          # 1 for 2nd array and 3 is the index number of 2nd array               
arr[0,2]          # 0 is for 1st array and 2 is the index  of 1st array             

7

In [46]:
arr1=np.array([[[2,3,4,5],[5,56,7,8],[2,4,5,6]]])
arr1[0,1,2]

7

In [62]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.argmax())
print(arr.argmin())
print(arr.size)


68
2
13.625
7
0
8


In [64]:
a=np.arange(4)
a.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [67]:
r=np.arange(48)
r.reshape(1,6,8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])